### ISSUE TITLE
Does this work with Django 2.1.5?

### ISSUE THREAD

**Issue by mcolacino57** [shaklev/django_range_slider#2]
I am trying to run the example program and am getting

TypeError at /test/
render() got an unexpected keyword argument 'renderer'

Plus additional diagnostics. Thinking this is because this was created for Django 1.x.x. Can you let me know if this is the case, and if so, would you consider updating to 2.1.x or suggesting how it might be done.

**Comment by shaklev** [comment]
@mcolacino57 yes this was initially created for Django 1.8 , i'm going to update it for Django 2.x today / tomorrow

**Comment by shaklev** [comment]
The plug-in is updated and now it's fully compatible with Django 2.x.

There was a change in Django 2.1 that caused the issue: https://docs.djangoproject.com/en/2.1/releases/2.1/#features-removed-in-2-1

The package is updated on PyPI as well so you can install it using pip ( 0.2.4 version ; the newest ). Let me know if it works for you so we can close the issue.

**Comment by mcolacino57** [comment]
Sorry to be troublesome but I am still getting the error. I have installed 0.2.4, as seen here:

(test_slider) MacBook-Pro15:test_slider mdcair$ pip show django_range_slider
Name: django-range-slider
Version: 0.2.4
Summary: A range-slider field for django , using jquery-ui
Home-page: https://github.com/shakle17/django_range_slider <https://github.com/shakle17/django_range_slider>
Author: Aleksandar Shaklev
Author-email: saklevaleksandar@gmail.com <mailto:saklevaleksandar@gmail.com>
License: UNKNOWN
Location: /Users/mdcair/.local/share/virtualenvs/test_slider-D6N6JbT3/lib/python3.7/site-packages


But when I run the server, and go to http://127.0.0.1:8000/test/ <http://127.0.0.1:8000/test/> I still get this:


TypeError at /test/
render() got an unexpected keyword argument 'renderer'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/test/ <http://127.0.0.1:8000/test/>
Django Version:	2.1.5
Exception Type:	TypeError
Exception Value:	
render() got an unexpected keyword argument 'renderer'
Exception Location:	/Users/mdcair/.local/share/virtualenvs/test_slider-D6N6JbT3/lib/python3.7/site-packages/django/forms/boundfield.py in as_widget, line 93
Python Executable:	/Users/mdcair/.local/share/virtualenvs/test_slider-D6N6JbT3/bin/python
Python Version:	3.7.0
Python Path:	
['/Users/mdcair/Desktop/django_range_slider-master/test_slider',
 '/Library/Frameworks/Python.framework/Versions/3.7/bin',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ply-3.11-py3.7.egg',
 '/Users/mdcair/.local/share/virtualenvs/test_slider-D6N6JbT3/lib/python37.zip',
 '/Users/mdcair/.local/share/virtualenvs/test_slider-D6N6JbT3/lib/python3.7',
 '/Users/mdcair/.local/share/virtualenvs/test_slider-D6N6JbT3/lib/python3.7/lib-dynload',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7',
 '/Users/mdcair/.local/share/virtualenvs/test_slider-D6N6JbT3/lib/python3.7/site-packages']
Server time:	Mon, 25 Mar 2019 17:08:38 +0000
Error during template rendering

In template /Users/mdcair/Desktop/django_range_slider-master/test_slider/slider_app/templates/base.html, error at line 11
render() got an unexpected keyword argument 'renderer'


1	{% load staticfiles %}
2	
3	<html>
4	<head>
5	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js <https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js>"></script>
6	<link href="http://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css <http://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css>" rel="stylesheet">
7	<script src="http://code.jquery.com/ui/1.12.0/jquery-ui.min.js <http://code.jquery.com/ui/1.12.0/jquery-ui.min.js>" ></script>
8	</head>
9	
10	<body>
11	{{ form.as_p}}
12	
13	</body>
14	</html>
15



Mike Colacino 
Haiku Partners
c (917) 664-4787 <tel:(917)%20664-4787>‌‌

**Comment by mcolacino57** [comment]
Also this is in the debug output:

/Users/mdcair/.local/share/virtualenvs/test_slider-D6N6JbT3/lib/python3.7/site-packages/django/forms/boundfield.py in as_widget
            renderer=self.form.renderer, ...
▼ Local vars <http://127.0.0.1:8000/test/#>
Variable	Value
attrs	
{'id': 'id_name_range_field', 'required': True}
only_initial	
False
self	
<django.forms.boundfield.BoundField object at 0x104200cc0>
widget	
<slider_app.widgets.RangeSlider object at 0x104200390>



Mike Colacino 
Haiku Partners
c (917) 664-4787 <tel:(917)%20664-4787>‌‌

**Comment by shaklev** [comment]
Hmm , can you make sure there aren't any cached files from the previous installation ( or reinstall it again ).
I've tested it with `python 3.5 , 3.6, 3.7 `& `Django > 1.8`  and it works with all versions. The error you are getting is the same is before so i assume there are some cached files.
Can you provide the code of the `render()` function in the `widgets.py` file from your locally installed library so i can see if the change was applied ?

**Comment by mcolacino57** [comment]
Here is widgets.py

from django import forms
from django.utils.safestring import mark_safe
import re

class RangeSlider(forms.TextInput):
    def __init__(self, minimum, maximum, step, elem_name,*args,**kwargs):
        widget = super(RangeSlider,self).__init__(*args,**kwargs)
        self.minimum = str(minimum)
        self.maximum = str(maximum)
        self.step = str(step)
        self.elem_name = str(elem_name)

    def render(self, name, value, attrs=None):
        s = super(RangeSlider, self).render(name, value, attrs)
        self.elem_id = re.findall(r'id_([A-Za-z0-9_\./\\-]*)"',s)[0]
        html = """<div id="slider-range-"""+self.elem_id+""""></div>
        <script>
        $('#id_"""+self.elem_id+"""').attr("readonly", true)
        $( "#slider-range-"""+self.elem_id + """" ).slider({
        range: true,
        min: """+self.minimum+""",
        max: """+self.maximum+""",
        step: """+self.step+""",
        values: [ """+self.minimum+""","""+self.maximum+""" ],
        slide: function( event, ui ) {
          $( "#id_"""+self.elem_id+"""" ).val(" """ + self.elem_name + """ "+ ui.values[ 0 ] + " - " + ui.values[ 1 ] );
        }
        });
        $( "#id_"""+self.elem_id+"""" ).val(" """ + self.elem_name + """ "+ $( "#slider-range-""" + self.elem_id + """" ).slider( "values", 0 ) +
        " - " + $( "#slider-range-"""+ self.elem_id + """" ).slider( "values", 1 ) );
        </script>
        """
        return mark_safe(s+html)


Mike Colacino 
Haiku Partners
c (917) 664-4787

**Comment by mcolacino57** [comment]
I had the wrong widgets. py in my test rlg. I replaced with the "renderer--none"version and now it works. Thanks and apologies for time wasting on the last go round. This one is closed. m

Mike Colacino 
Haiku Partners
c (917) 664-4787

**Comment by shaklev** [comment]
Yes the attribute `renderer` is required from django>2.1

**Comment by mcolacino57** [comment]
To connect this into an existing Django project would require changes to base.html (adding the css and query), the addition of widget.py and fields.py, all of which is clear. I’m having difficulty figuring out what needs doing on forms.py and views.py, since your use of Meta and calling the super doesn’t seem to work when I transcribe it to my forms.py. Also in the html to display the slider I’m not using as_p, naturally, so how to get the slider displayed isn’t clear. Could you give me some pointers toward understanding. Thanks; realize this isn’t your job but I think this would help others in the spirit of your prior efforts. 


Mike Colacino 
Haiku Partners
c (917) 664-4787 <tel:(917)%20664-4787>‌‌

**Comment by shaklev** [comment]
@mcolacino57  The `views.py` and `forms.py` files are just used for the `test_slider` application, to show a simple usage of the slider widget/field.
Not sure exactly how are you rendering the fields in your template , but here is an example ( if you have some kind of form ):
-  in your `forms.py` you would have an example form
```
Class TestForm(forms.Form):
     # other fields
     label_range_field = RangeSliderField(label=True,minimum=1,maximum=10)
```

- in your `example.html` ( the template file where you'll render your field )
```
... html code
<form>
{ form.label_range_field } // will render only the label_range_field ( the slider )
</form>
.... html code
```

**Comment by mcolacino57** [comment]
When I attempt this, I get a character field rather than a slider. Can you steer me in the right direction?


Here is my forms.py:

from django import forms
from .fields import RangeSliderField
from .models import Comment

class CommentForm(forms.Form):
    author = forms.CharField(max_length=60,
        widget=forms.TextInput(attrs={"class": "form-control","placeholder": "Your Name"}))
    body = forms.CharField(widget=forms.Textarea(attrs={
        "class": "form-control",
        "placeholder": "Leave a comment!"}))
    slider_val= RangeSliderField(label=True,minimum=1,maximum=10)

...and my rendering .html looks like this:

{% extends "base.html" %}
{% block page_content %}
<div class="col-md-8 offset-md-2">
    <h1>{{ post.title }}</h1>
    <small>
        {{ post.created_on.date }} |&nbsp;
        Categories:&nbsp;
        {% for category in post.categories.all %}
        <a href="{% url 'blog_category' category.name %}">
            {{ category.name }}
        </a>&nbsp;
        {% endfor %}
    </small>
    <p>{{ post.body | linebreaks }}</p>
    <h3>Leave a comment:</h3>
    <form action="/blog/{{ post.pk }}/" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.author }}
        </div>
        <div class="form-group">
            {{ form.body }}
        </div>
        <div class="form-group">
            {{ form.slider_val }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <h3>Comments:</h3>
    {% for comment in comments %}
    <p>
        On {{comment.created_on.date }}&nbsp;
        <b>{{ comment.author }}</b> wrote:
    </p>
    <p>{{ comment.body }}</p>
    <hr>
    {% endfor %}
</div>
{% endblock %}

And for good measure, here is my base.html, where I have tried to add “your” javascript stuff to what is needed for bootstrap (could there be some conflict here between what bootstrap is loading and what you have in your example?)

{% load staticfiles %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css <https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css>" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'project_index' %}">RP Portfolio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'project_index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog_index' %}">Blog</a>
            </li>
          </ul>
        </div>
    </div>

</nav>

<div class="container">
    {% block page_content %}{% endblock %}
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js <https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js>"></script>
<link href="http://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css <http://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css>" rel="stylesheet">
<script src="http://code.jquery.com/ui/1.12.0/jquery-ui.min.js <http://code.jquery.com/ui/1.12.0/jquery-ui.min.js>" ></script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js <https://code.jquery.com/jquery-3.3.1.slim.min.js>" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js <https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js>" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js <https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js>" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


Mike Colacino 
Haiku Partners
c (917) 664-4787 <tel:(917)%20664-4787>‌‌

**Comment by shaklev** [comment]
@mcolacino57 You have typos in your `script` and  `link` tags that you've provided me in your `base.html` ( i'm assuming this is just when copying the `base.html` content to github; additionally would be nice if you use code markups , for clear look ).

So after testing the code you've provided me with seems like the issue is you are including:
 - jquery 3.3.1 slim min (seems to be the issue)  
```
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>  
```  
But i'm not exactly sure why are you including the `3.3.1 slim min version of jquery `, when you already have included the `jquery 3.3.1 min version`

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
```
Just remove the `jquery-3.3.1.slim.min.js` and you should be good.

**Comment by mcolacino57** [comment]
I don’t want to keep wasting your time for free. Is there a way (PayPal,Venmo e.g) that I could compensate you for your help? If you let me know method/rate/time I will send $ along.

I removed the redundant javascript call, but it’s still rendering as a text field. Data entered into the text field is written to the model database correct. As you can see, I am building this with bootstrap, which requires its own version of min.js. Wonder if there is some namespace conflict where the bootstrap.min.js is overriding?





Here is the page source:


<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css <https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css>" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/projects/">RP Portfolio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/projects/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/blog/">Blog</a>
            </li>
          </ul>
        </div>
    </div>

</nav>

<div class="container">
    
<div class="col-md-8 offset-md-2">
    <h1>Barr-non</h1>
    <small>
        April 4, 2019 |&nbsp;
        Categories:&nbsp;
        
        <a href="/blog/MAGA/">
            MAGA
        </a>&nbsp;
        
    </small>
    <p><p>orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p></p>
    <h3>Leave a comment:</h3>
    <form action="/blog/3/" method="post">
        <input type="hidden" name="csrfmiddlewaretoken" value="9IIgKaMKbmVx51rPG9oro5RpRROfwJc8HSrlkhF8Zu6EawVQavW82kgPtpiY0ACp">
        <div class="form-group">
            <input type="text" name="author" class="form-control" placeholder="Your Name" maxlength="60" required id="id_author">
        </div>
        <div class="form-group">
            <textarea name="body" cols="40" rows="10" class="form-control" placeholder="Leave a comment!" required id="id_body">
</textarea>
        </div>
        <div class="form-group">
            <input type="text" name="slider_val" required id="id_slider_val"><div id="slider-range-slider_val"></div>
        <script>
        $('#id_slider_val').attr("readonly", true)
        $( "#slider-range-slider_val" ).slider({
        range: true,
        min: 1,
        max: 10,
        step: 1,
        values: [ 1,10 ],
        slide: function( event, ui ) {
          $( "#id_slider_val" ).val("  "+ ui.values[ 0 ] + " - " + ui.values[ 1 ] );
        }
        });
        $( "#id_slider_val" ).val("  "+ $( "#slider-range-slider_val" ).slider( "values", 0 ) +
        " - " + $( "#slider-range-slider_val" ).slider( "values", 1 ) );
        </script>
        
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <h3>Comments:</h3>
    
    <p>
        On April 7, 2019&nbsp;
        <b>mikey</b> wrote:
    </p>
    <p>This sux; this is great</p>
    <hr>
    
    <p>
        On April 9, 2019&nbsp;
        <b>Michael</b> wrote:
    </p>
    <p>Rock on</p>
    <hr>
    
</div>

</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js <https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js>"></script>
<link href="http://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css <http://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css>" rel="stylesheet">
<script src="http://code.jquery.com/ui/1.12.0/jquery-ui.min.js <http://code.jquery.com/ui/1.12.0/jquery-ui.min.js>" ></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js <https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js>" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js <https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js>" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>



Mike Colacino 
Haiku Partners
c (917) 664-4787 <tel:(917)%20664-4787>‌‌

**Comment by mcolacino57** [comment]
This is beyond odd. So I took the html generated by Django after the source had been rendered in Safari. In other words I did “show source”  in Safari and copied and pasted that into Dreamweaver, and as expected the slider showed up as a text field. Then I slipped and pasted it a second time..and it suddenly worked. So two sets of the same html code in line works but one copy doesn’t.

This is one of the strangest things I’ve seen. If you respond affirmatively to my last email I will send you the “working” html and perhaps you can figure out what’s wrong with the “single” version.  m



Mike Colacino 
Haiku Partners
c (917) 664-4787 <tel:(917)%20664-4787>‌‌

**Comment by shaklev** [comment]
Thanks for the offer but since i'm using a lot of open source libs , i'm trying to contribute as much as i can.
Regarding the code , you can send me the templates and i'll try to help.

**Comment by mcolacino57** [comment]
I put the code up to GitHub and invited you as a collaborator. The slider is in the blog app. The template that attempts to display the slider is in blog_detail.html, and the javascript and css stuff is of course in base.html in personal_portfolio.


Mike Colacino 
Haiku Partners
c (917) 664-4787 <tel:(917)%20664-4787>‌‌

**Comment by mcolacino57** [comment]
I think I got it largely working. Had to figure out which css and js files were needed and put them in a static directory to get it all working, but I now have a slider.

I invited you to the repo but you can ignore.

Thanks for the help.


Mike Colacino 
Haiku Partners
c (917) 664-4787 <tel:(917)%20664-4787>‌‌

**Comment by shaklev** [comment]
@mcolacino57  I've cloned your repo and tested the `/blog/1/` route where the `blog_detail.html` is rendered , the slider was rendering as char field , but if you move the imports:
```
- jquery
- jqueru-ui ( js/css)
```
at the start of the template ( after `{% load staticfiles%}` ) every script/css is loaded properly , probably you had issues with the imports.

Feel free to write if you need further help.

Alex
